### ISSUE TITLE
Given the small 'g' acceleration due to gravity, can we calculate the mass and dimensions of the object that is the reason for that value of g?

### ISSUE THREAD

**Issue by malisetti** [timhutton/GravityIsNotAForce#1]

**Comment by timhutton** [comment]
No, because gravity changes with distance - it decreases in strength as you move away from the mass, by the inverse-square law.

(Btw, our model assumes a constant gravitational field - i.e. that the mass is far enough away that we can ignore the change in g over the region of interest.)
